메인페이지 작업입니다. 헤더부분 필요하신 분들 위해 풀 리퀘부탁드립니다
Cameron-86/B04_project pull request #5
Opened 2024-06-04 07:47 UTC by Ahnjonghyun87

기능 구현 안된 것들은 하단의 최신, 인기 (view) 기능 버튼 동작 안합니다. 코드리팩토링이 안된 상태입니다.
하단의 글은 더미 데이터고 상단 글은 데이터베이스를 계속 쓸 예정입니다

남은 todo list:

게임정보 페이지 db 업데이트 후 모달로 간략 상세페이지를 클릭시 오픈

하단 기능버튼

코드리팩토링

2024-06-04 11:36 UTC, mangmuse approved these changes
고생하셨습니다!

2024-06-04 16:53 UTC, hyeonseok98 requested changes
1. hooks의 useFind는 어떤걸 찾는지 조금 더 명확하게 파일명을 지어주시면 좋을 것 같아요.
2. components 안에 메인페이지에 관련된건 main이나 home 등의 폴더를 만드셔서 안에 몰아주시면 감사하겠습니다!

+ api폴더는 api의 값만 가져올 수 있도록 리팩토링되면 더 좋을 것 같습니다!

2024-06-04 16:53 UTC, hyeonseok98 commented on src/api/FakeArticle.jsx
> +  background-color: #2a2829;
직접적으로 컬러변수를 사용하는 것 보다 var(--color-black-50)으로 사용해주시면 좋을 것 같아요. 다른 컬러들에 대해서도요!

2024-06-04 16:53 UTC, hyeonseok98 commented on src/api/GameRankFetchData.jsx
> +    font-size: 20px;
font-size는 rem단위로 부탁드릴게요!

2024-06-04 16:53 UTC, hyeonseok98 commented on src/pages/HomePage/HomePageStyle.jsx
> +  .login-buttons {
이 곳 버튼과 아래의 search-MiddleContainer의 경우 div {}로 사용해도 스타일을 정의할 수 있어 다른 스타일과 통일성을 맞춰주는 게 좋아보여요! 고려 부탁드립니다

2024-06-04 16:53 UTC, hyeonseok98 commented on src/pages/HomePage/HomePageStyle.jsx
> +  width: 3rem;
width와 height는 이 부분이 상대적 단위로 사용해야하는 부분이 아니라면 다른 곳과 동일하게 px로 사용해도 좋을 것 같아요!

2024-06-04 16:53 UTC, hyeonseok98 commented on src/hooks/useFind.js
> +    return data;
이 부분은 data와 searchQuery 중 하나라도 비어있다면 return을 하기 위한 코드로 보이는데, data가 없을 경우는 빈 배열이 반환되어, 빈 값을 가지고 로직을 처리하게 될 수도 있을 것 같아요.
한 번 확인 부탁드립니다!

2024-06-05 05:20 UTC, Ahnjonghyun87 commented on src/hooks/useFind.js
> +    return data;
뒤늦게 확인중입니다 모든 요청사항 수정하겠습니다

2024-06-05 05:21 UTC, Ahnjonghyun87 commented on src/pages/HomePage/HomePageStyle.jsx
> +  width: 3rem;
넵

2024-06-05 05:21 UTC, Ahnjonghyun87 commented on src/pages/HomePage/HomePageStyle.jsx
> +  .login-buttons {
네

2024-06-05 05:21 UTC, Ahnjonghyun87 commented on src/api/GameRankFetchData.jsx
> +    font-size: 20px;
네

2024-06-05 05:21 UTC, Ahnjonghyun87 commented on src/api/FakeArticle.jsx
> +  background-color: #2a2829;
네

2024-06-05 05:44 UTC, Ahnjonghyun87 commented on src/pages/HomePage/HomePageStyle.jsx
> +  width: 3rem;
수정했습니다

2024-06-05 07:53 UTC, Ahnjonghyun87 commented on src/hooks/useFind.js
> +    return data;
(!data || !searchQuery || data.length === 0) 조건문을 수정하여 빈 배열을 로직으로 처리하는 문제를 방지했습니다

2024-06-05 08:12 UTC, Ahnjonghyun87 commented on src/pages/HomePage/HomePageStyle.jsx
> +  .login-buttons {
const StSearchMiddleContainer = styled.div`
  position: relative;

  left: 0px;
  right: 20px;
  display: flex;
  gap: 0px;

  button {
    height: 48px;
    font-size: 15px;
    font-weight: bold;
    margin-left: 20px;
    padding: 5px 25px;
    border: none;
    border-radius: 25px;
    background-color: #ffbf00;
    color: white;
    cursor: pointer;

    &:hover {
      background-color: #ffcf3e;
    }
  }
`;const StLoginButtons = styled.div`
  display: flex;
  gap: 10px;

  button {
    padding: 10px 18px;
    border: none;
    border-radius: 25px;
    background-color: #363636;
    color: #ffffff;
    cursor: pointer;
    height: 48px;
    font-size: 15px;
    font-weight: bold;
    transition: 0.4s;

    &:hover {
      background-color: #666666;
    }
  }
`; 수정했습니다

2024-06-05 10:45 UTC, Ahnjonghyun87 commented on src/api/FakeArticle.jsx
> +  background-color: #2a2829;
반영했습니다

2024-06-05 11:21 UTC, hyeonseok98 approved these changes

2024-06-05 15:20 UTC, Cameron-86 approved these changes
수고하셨습니다

2024-06-05 15:40 UTC, merged